# Build stage for dependencies
FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

# Final test stage
FROM golang:alpine

RUN apk add ffmpeg

WORKDIR /app
COPY --from=builder /go/pkg /go/pkg
COPY . .

CMD go test ./pkg/mediorum/... -count 1 -timeout 60s
