root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/audiusd cmd/audiusd/main.go"
bin = "./tmp/audiusd"
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
exclude_dir = ["cmd/audius-ctl"]
delay = 1000
kill_delay = 500
stop_on_error = true
log = "air.log"
send_interrupt = true

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 