// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: writes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlaysByBlockRange = `-- name: DeletePlaysByBlockRange :exec
delete from etl_plays
where block_height between $1 and $2
`

type DeletePlaysByBlockRangeParams struct {
	BlockHeight   int64
	BlockHeight_2 int64
}

// delete plays by block height range (useful for reindexing)
func (q *Queries) DeletePlaysByBlockRange(ctx context.Context, arg DeletePlaysByBlockRangeParams) error {
	_, err := q.db.Exec(ctx, deletePlaysByBlockRange, arg.BlockHeight, arg.BlockHeight_2)
	return err
}

const insertPlay = `-- name: InsertPlay :one
insert into etl_plays (
    address,
    track_id,
    city,
    region,
    country,
    played_at,
    block_height,
    tx_hash
) values (
    $1, $2, $3, $4, $5, $6, $7, $8
) returning id, address, track_id, city, region, country, played_at, block_height, tx_hash, created_at, updated_at
`

type InsertPlayParams struct {
	Address     string
	TrackID     string
	City        string
	Region      string
	Country     string
	PlayedAt    pgtype.Timestamp
	BlockHeight int64
	TxHash      string
}

// insert a new play record
func (q *Queries) InsertPlay(ctx context.Context, arg InsertPlayParams) (EtlPlay, error) {
	row := q.db.QueryRow(ctx, insertPlay,
		arg.Address,
		arg.TrackID,
		arg.City,
		arg.Region,
		arg.Country,
		arg.PlayedAt,
		arg.BlockHeight,
		arg.TxHash,
	)
	var i EtlPlay
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.TrackID,
		&i.City,
		&i.Region,
		&i.Country,
		&i.PlayedAt,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlays = `-- name: InsertPlays :many
insert into etl_plays (
    address,
    track_id,
    city,
    region,
    country,
    played_at,
    block_height,
    tx_hash
) values (
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::text[]),
    unnest($5::text[]),
    unnest($6::timestamp[]),
    unnest($7::bigint[]),
    unnest($8::text[])
)
on conflict do nothing
returning id, address, track_id, city, region, country, played_at, block_height, tx_hash, created_at, updated_at
`

type InsertPlaysParams struct {
	Column1 []string
	Column2 []string
	Column3 []string
	Column4 []string
	Column5 []string
	Column6 []pgtype.Timestamp
	Column7 []int64
	Column8 []string
}

// insert multiple play records with batch size control
func (q *Queries) InsertPlays(ctx context.Context, arg InsertPlaysParams) ([]EtlPlay, error) {
	rows, err := q.db.Query(ctx, insertPlays,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EtlPlay
	for rows.Next() {
		var i EtlPlay
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.PlayedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLatestIndexedBlock = `-- name: UpdateLatestIndexedBlock :one
insert into etl_latest_indexed_block (block_height)
values ($1)
returning id, block_height, created_at, updated_at
`

// update latest indexed block
func (q *Queries) UpdateLatestIndexedBlock(ctx context.Context, blockHeight int64) (EtlLatestIndexedBlock, error) {
	row := q.db.QueryRow(ctx, updateLatestIndexedBlock, blockHeight)
	var i EtlLatestIndexedBlock
	err := row.Scan(
		&i.ID,
		&i.BlockHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
