# Build stage for dependencies
FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

# Final test stage
FROM golang:alpine

WORKDIR /app
COPY --from=builder /go/pkg /go/pkg
COPY . .

ENV discoveryOneGRPC=audiusd-1:50051
ENV discoveryOneJRPC=http://audiusd-1:26657
ENV discoveryOneOAPI=audiusd-1:26659

ENV contentOneGRPC=audiusd-2:50051
ENV contentOneJRPC=http://audiusd-2:26657
ENV contentOneOAPI=audiusd-2:26659

ENV contentTwoGRPC=audiusd-3:50051
ENV contentTwoJRPC=http://audiusd-3:26657
ENV contentTwoOAPI=audiusd-3:26659

ENV contentThreeGRPC=audiusd-4:50051
ENV contentThreeJRPC=http://audiusd-4:26657
ENV contentThreeOAPI=audiusd-4:26659

CMD go test ./pkg/core/... -count 1 -timeout 60s
