version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - sandbox-core-net

  prod-sandbox:
    extends:
      service: base-sandbox
    container_name: prod-sandbox
    env_file:
      - ./dev_config/prod-sandbox.env
    profiles:
      - prod

  stage-sandbox:
    extends:
      service: base-sandbox
    container_name: stage-sandbox
    env_file:
      - ./dev_config/stage-sandbox.env
    profiles:
      - stage

  dev-sandbox:
    extends:
      service: base-sandbox
    container_name: dev-sandbox
    env_file:
      - ./dev_config/dev-sandbox.env
    profiles:
      - dev

  base-sandbox:
    build:
      context: ../../../
      dockerfile: ./cmd/core/infra/Dockerfile.dev
    volumes:
      - /tmp/audius-core:/audius-core
      - /tmp/audius-core:/tmp
    restart: unless-stopped
    networks:
      - sandbox-core-net
    environment: []
    profiles:
      - base

  postgres:
    image: postgres:latest
    container_name: sandbox-core-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5437:5432"
    networks:
      - sandbox-core-net

networks:
  sandbox-core-net:
