services:
  audiusd:
    container_name: audiusd
    build:
      context: .
      dockerfile: ./cmd/audiusd/Dockerfile
      args:
        git_sha: '${GIT_COMMIT}'
    restart: unless-stopped
    profiles:
      - discovery
      - storage
    depends_on:
      db:
        condition: service_healthy
